### ISSUE TITLE
Having to sleep when waiting for web scrape

### ISSUE THREAD

**Issue by timcop** [timcop/ReciPlease#13]
We shouldn't have to hard code a sleep command while waiting for the web scrape as this may take quicker/longer on different devices/connections.

**Comment by ethan-fraser** [comment]
Is this related to #14?

**Comment by timcop** [comment]
No sorry should have been more specific. currently we perform a sleep function for 3 seconds while the web scraping takes place, this is due to multithreading and the program being able to access Data.Ingredients while the scrape is still taking place on another thread.
