### ISSUE TITLE
Countdown API blocked my IP 

### ISSUE THREAD

**Issue by timcop** [timcop/ReciPlease#14]
I'm no longer able to web scrape on my computer at home and can't even access their regular online website, this is something I brought up in our first meeting: whether or not Countdown will actually want us accessing their API...

**Comment by ethan-fraser** [comment]
Most likely rate limiting. Rather than scrape for all products, let's try to keyword searching each time the user enters an ingredient.

**Comment by timcop** [comment]
Update: Was able to access countdown again today and web scraping was working for #urls ~ 60, when I tried #urls ~ 120 I got blocked again with this error when trying to access countdown.co.nz 
![Screen Shot 2021-08-16 at 12 47 45 PM](https://user-images.githubusercontent.com/70932357/129498332-8dfb1d07-5da5-4f09-a2e1-0074d30cca30.png)

**Comment by timcop** [comment]
Another update, I was only blocked for 10-15minutes (which happened last night) and when testing a single url (page=2) it works fine. I must have had the typos in my urls when I went to test it again last night when I was unblocked. 

So now we know that accessing >14 urls at a time results in likely rate limiting with ip being blocked temporarily for 10-15 minutes. For the Beta we should just stick with the 14 urls that were working but will need to find a workaround for next release, I'm thinking possibly spacing out the requests in chunks of ~15 urls?
